language: generic
services:
- docker
cache:
  directories:
  - $HOME/.stack
addons:
  apt:
    packages:
    - libgmp-dev
    - upx-ucl
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- |
  [[ "$TRAVIS_TAG" = "" || \
     "$(stack query locals checkmate version)" == "'$TRAVIS_TAG'" ]]
- '[[ "$TRAVIS_TAG" = "" ]] || ! grep -i "to be released" CHANGELOG.md'
- stack --no-terminal test --haddock --no-haddock-deps
- |
  if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    git diff "$TRAVIS_COMMIT_RANGE" | stack exec -- checkmate github \
      --token "$CHECKMATE_GITHUB_ACCESS_TOKEN" \
      --login "${TRAVIS_REPO_SLUG%%/[^/]*}" \
      --repo "${TRAVIS_REPO_SLUG#[^/]*/}" \
      --pr "$TRAVIS_PULL_REQUEST"
  fi
before_deploy:
- mkdir -p /tmp/checkmate-build
- docker build -t checkmate-binary-build .
- docker run checkmate-binary-build cat /root/.local/bin/checkmate > /tmp/checkmate-build/checkmate-"$(docker run checkmate-binary-build bash -c 'echo $(uname -s | tr "[A-Z]" "[a-z]")-$(uname -m)')"
- chmod +x /tmp/checkmate-build/checkmate-*
- upx-ucl -9 /tmp/checkmate-build/checkmate-*
deploy:
- provider: releases
  api_key: "$GITHUB_ACCESS_TOKEN"
  file_glob: true
  file: /tmp/checkmate-build/checkmate-*
  skip_cleanup: true
  on:
    tags: true
after_deploy:
# We don't use Travis' Hackage provider since we shouldn't build dists twice
- mkdir -p ~/.stack/upload
- |
  python -c 'import json, os; print(json.dumps({"username": os.environ["HACKAGE_USERNAME"], "password": os.environ["HACKAGE_PASSWORD"]}))' > ~/.stack/upload/credentials.json
- "sed -i 's/^- -Werror$//g' package.yaml"   # Hackage disallows -Werror
- stack --no-terminal sdist --ignore-check
- stack --no-terminal upload --ignore-check --no-signature .
