name: checkmate
version: '0.4.0'
synopsis: Generate checklists relevant to a given patch
category: Development
author: Hong Minhee
maintainer: hong.minhee@gmail.com
copyright: (c) 2017 Hong Minhee
license: AGPL-3
github: spoqa/checkmate
stability: alpha
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- base >= 4.7 && < 5
- diff-parse >= 0.2.1 && < 0.3.0
- directory == 1.3.*
- filepath >= 1.4.1.1 && < 2.0.0
- megaparsec == 6.5.*
- text == 1.*
flags:
  static:
    description: Static link
    manual: true
    default: false
when:
- condition: os(darwin)
  else:
    ghc-options:
    - -Werror
  then:
    ghc-options:
    - -Werror
    - -optP-Wno-nonportable-include-path
    # The above option works around https://github.com/haskell/cabal/issues/4739
library:
  source-dirs: src
  dependencies:
  - containers >= 0.5.7.1 && < 0.6.0.0
  - github == 0.19.*
  - monad-parallel >= 0.7.2.2 && < 0.8.0.0
  ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
executables:
  checkmate:
    main: Main.hs
    source-dirs: app
    dependencies:
    - checkmate
    - optparse-applicative >= 0.13.2.0 && < 0.15.0.0
    - process >= 1.6.1.0 && < 1.7.0.0
    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        # Static link
        - -static
        - -optl-static
        - -optl-pthread
        - -optc-Os
        - -fPIC
      else:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
    - bytestring >= 0.10.8.1 && < 0.11
    - checkmate
    - file-embed >= 0.0.10 && < 0.1.0
    - hspec >= 2.4.4 && < 3.0.0
    - hspec-megaparsec >= 1.0.0 && < 1.1.0
    - interpolatedstring-perl6 == 1.*
    - QuickCheck >= 2.9.2 && < 3.0.0
    - quickcheck-text >= 0.1.2.1 && < 0.2.0.0
    - temporary >= 1.2.1 && < 1.3.0.0
    ghc-options:
    - -Wall
    - -fno-warn-incomplete-uni-patterns
    - -fno-warn-missing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-orphans
  hlint:
    main: hlint.hs
    dependencies:
    - hlint >= 2.0.9 && < 3
