name: checkmate
version: '0.1.0'
synopsis: Generate checklists relevant to a given patch
category: Development
author: Hong Minhee
maintainer: hong.minhee@gmail.com
copyright: (c) 2017 Hong Minhee
license: GPL-3
github: spoqa/checkmate
stability: alpha
extra-source-files:
- README.md
dependencies:
- base >= 4.7 && < 5
- diff-parse >= 0.2.1 && < 0.3.0
- directory == 1.3.*
- filepath >= 1.4.1.1 && < 2.0.0
- megaparsec >= 5.3.1 && < 5.4.0
- range >= 0.1.2 && < 0.2.0
- text == 1.*
ghc-options:
- -Wall
- -Werror
library:
  source-dirs: src
  dependencies:
  - containers >= 0.5.7.1 && < 0.6.0.0
  - monad-parallel >= 0.7.2.2 && < 0.8.0.0
  ghc-options:
  - -fwarn-incomplete-uni-patterns
executables:
  checkmate:
    main: Main.hs
    source-dirs: app
    dependencies:
    - checkmate
    - github == 0.16.*
    - optparse-applicative >= 0.13.2.0 && < 0.15.0.0
    ghc-options:
    - -fwarn-incomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - bytestring >= 0.10.8.1 && < 0.11
    - checkmate
    - file-embed >= 0.0.10 && < 0.1.0
    - hspec >= 2.4.4 && < 3.0.0
    - hspec-megaparsec >= 0.3.1 && < 0.4.0
    - interpolatedstring-perl6 == 1.*
    - QuickCheck >= 2.9.2 && < 3.0.0
    - quickcheck-text >= 0.1.2.1 && < 0.2.0.0
    - temporary >= 1.2.1 && < 1.3.0.0
    ghc-options:
    - -fno-warn-incomplete-uni-patterns
    - -fno-warn-missing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-orphans
  hlint:
    main: HLint.hs
    source-dirs: test
    dependencies:
    - hlint >= 2.0.9 && < 3
