resolver: lts-12.8
packages:
- .
- location:
    git: git://github.com/mulby/diff-parse.git
    commit: a2218afd2bb56e9afe96e543dad72abf5a881dfc
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
ghc-options:
  "$locals": -fhide-source-paths
# http://hsyl20.fr/home/posts/2018-01-15-ghc-hiding-source-and-object-paths.html
require-stack-version: ">=1.6.3"
